### ISSUE TITLE
there will be freeze on some low phones

### ISSUE THREAD

**Issue by yangliguo7** [megasanjay/vue3-marquee#112]
Thanks code.

I found that there will be freeze on some low phones

https://github.com/megasanjay/vue3-marquee/blob/6cb63103711d5a77905e8f44bfad9086c82a7299/packages/vue3-marquee/src/vue3-marquee.vue#L307-L314

There will be a frame freeze for a period of time when text scrolling

Is this a problem with the phone? cpu not good ?

or 

hava some way to avoid this problem ?

**Comment by megasanjay** [comment]
Are you using this for only text or something more dynamic?

**Comment by yangliguo7** [comment]
just text and image. like that

```
    <Marquee>
      <div class="item" v-for="(item, index) in arr" :key="index">
        <img src="xxxxx" width="16" height="16" />
        <div>xxxxx</div>
      </div>
    </Marquee>
```

bus the text content is large

the `arr`  is an array of length 10 . 

This only happens on some phones. I think it might have something to do with the phone's GPU

Is there any way to circumvent this problem?

I can't find any alternatives to fix this right now . 😔. I have the same problem with canvas

**Comment by megasanjay** [comment]
To add some info to this, does a carousel on autoplay work for this issue?
