### ISSUE TITLE
nuxt3 error using Vue3Marquee.client.ts -> Vue3Marquee.ts ok

### ISSUE THREAD

**Issue by oripka** [megasanjay/vue3-marquee#117]
I did setup the project as described in the guide for nuxt3: https://vue3-marquee.vercel.app/guide.html#nuxt-3

But this gives error on the server side.
```
[Vue warn]: Failed to resolve component: Vue3Marquee                                                                                                  15:47:20
If this is a native custom element, make sure to exclude it from component resolution via compilerOptions.isCustomElement.
[Vue warn]: Non-function value encountered for default slot. Prefer function slots for better performance.                                            15:47:20
[Vue warn]: Component <Anonymous> is missing template or render function.                                                                             15:47:20
[Vue warn]: Non-function value encountered for default slot. Prefer function slots for better performance.                                            15:47:20
[Vue warn]: Component <Anonymous> is missing template or render function.                                                                             15:47:20
[Vue warn]: Non-function value encountered for default slot. Prefer function slots for better performance.
```

Changing Vue3Marquee.client.ts to Vue3Marquee.ts removes the errors.

**Comment by eris-vn** [comment]
helpful

**Comment by megasanjay** [comment]
Thank you for the issue report. Does it cause any issues if you resize the window with your updated plugin file? If there are no hydration warnings I'll go ahead and update the docs text to reflect this change.

**Comment by go4cas** [comment]
I had the same error, and the suggestion of removing "client" from the file name, did remove that error. But, I still get the following on the line `nuxtApp.vueApp.use(Vue3Marquee)`:

"Expected 2 arguments, but got 1.ts(2554)
runtime-core.d.ts(712, 61): Arguments for the rest parameter 'options' were not provided."

Adding an empty object for the options does not seem to work.

Any ideas?

**Comment by go4cas** [comment]
Thanks, @megasanjay! That worked!

**Comment by irux** [comment]
I am still having this issue with `use(Vue3Marquee, { name: "Vue3Marquee" })` any idea what could make this happen ?

**Comment by megasanjay** [comment]
> @megasanjay I am still having this issue with `use(Vue3Marquee, { name: "Vue3Marquee" })` any idea what could make this happen ?

Are you following the directions here? https://vue3-marquee.vercel.app/introduction/installation
