### ISSUE TITLE
The first items are not visible

### ISSUE THREAD

**Issue by S-Masoud-Emamian** [megasanjay/vue3-marquee#129]
I have 57 items. but the first items about 20 items not visible. my page when loaded It starts to be displayed from item 21.

`
<template lang="pug">
.slider.slider__doctors
    ul(style="flex")
      //Vue3Marquee(:duration="100")
      li(v-for="doctor in doctors")
        span.slider__doctors__name {{ doctor.full_name }}
        span.slider__doctors__expert  ({{ doctor.expert_type }} {{ doctor.expert }})

      //Vue3Marquee(direction="reverse")
      //  li(v-for="(doctor, index) in doctors" :key="index")
      //      span.slider__doctors__name {{ doctor.full_name }}
      //      span.slider__doctors__expert  ({{ doctor.expert }})

</template>

<script lang="ts">
import { defineComponent, ref, toRefs, watch } from "vue";
import { Vue3Marquee } from "vue3-marquee";
import "vue3-marquee/dist/style.css";

import { fileBaseUrl } from "@/services/appConfig";

export default defineComponent({
  components: {
    Vue3Marquee,
  },
  props: {
    doctors: {
      type: Array,
      default: () => [],
    },
  },
  setup(props, { emit }) {
    return {
      fileBaseUrl,
    };
  },
});
</script>

<style></style>
`

my style:

`
#main .slider__doctors {
  padding: 30px;
  background-color: #08B89D;
  position: fixed;
  bottom: 0px;
  right: 0px;
  left: 0px;
  z-index: 200;
  display: -webkit-box;
  display: -webkit-flex;
  display: -ms-flexbox;
  display: flex;
  overflow: hidden;
  width: 100%;
  -webkit-box-pack: start;
  -webkit-justify-content: flex-start;
  -ms-flex-pack: start;
  justify-content: flex-start;
  -webkit-box-align: center;
  -webkit-align-items: center;
  -ms-flex-align: center;
  align-items: center;
}
#main .slider__doctors ul {
  position: absolute;
  top: 8px;
  left: 0px;
  white-space: nowrap;
  will-change: transform;
  animation: marquee-horizontal-alt 120s linear infinite;
  display: -webkit-box;
  display: -webkit-flex;
  display: -ms-flexbox;
  list-style: none;
  display: flex;
  -webkit-box-pack: start;
  -webkit-justify-content: flex-start;
  -ms-flex-pack: start;
  justify-content: flex-start;
  -webkit-box-align: center;
  -webkit-align-items: center;
  -ms-flex-align: center;
  align-items: center;
}
#main .slider__doctors ul li {
  margin-right: 2vw;
  -webkit-box-flex: 0;
  -webkit-flex: 0 0 auto;
  -ms-flex: 0 0 auto;
  flex: 0 0 auto;
  color: #fff;
  text-transform: uppercase;
}`

**Comment by megasanjay** [comment]
Can you create a reproduction for me to test?
