### ISSUE TITLE
clone=true with a short text clones infinitely when wrapped in a flex container

### ISSUE THREAD

**Issue by Patrick-Sachs** [megasanjay/vue3-marquee#13]
**Describe the bug**
When using `clone=true` and wrapping a marquee with a short text (e.g. `123`) in a container with `display: flex`, the contents of the marquee are cloned near infinitely.

**To Reproduce**

1. Create a vue3-marquee with `:clone="true"` and `123` in its default slot
2. Wrap it in a div with `style="display: flex;"`
3. The marquee now keeps cloning the content inside of it for ever

Can be reproduced in the Sandbox.

**Expected behavior**
The marquee should behave as normal.

**Screenshots**
<img width="1038" alt="Bildschirmfoto 2022-03-01 um 11 32 13" src="https://user-images.githubusercontent.com/33065264/156153255-2f6c846a-191d-41c6-83b0-a61ea80d5461.png">

(note the long scrollbar in the screenshot, it keeps getting longer)

**Desktop (please complete the following information):**

- OS: macOS 12.2.1 (21D62)
- Browser Google Chrome 
- Version 98.0.4758.109 (Official Build) (x86_64)

**Smartphone (please complete the following information):**

- Device: n/a
- OS: n/a
- Browser n/a
- Version n/a

**Additional context**
n/a

**Comment by megasanjay** [comment]
@Patrick-Sachs Thank you for using this library. I just took a look at your example and I noticed the same behavior. I have a fix that you can do on your side in the meantime that looks like it fixes the issue. I'll need a bit more time to see what the root cause is and implement a solution.

In the meantime you could do something like this:

```html
<div style="display: flex">
    <div style="width: 100%">
      <Vue3Marquee :clone="true">
        <span>123</span>
      </Vue3Marquee>
    </div>
  </div>
```

**Comment by Patrick-Sachs** [comment]
Hello @megasanjay!

Thanks for the quick reply! We just tried the workaround but it does not change the behavior on our end. Thank you for your time working on this, it's much appreciated! :)

**Comment by megasanjay** [comment]
Hi, @Patrick-Sachs Thank you for your patience. I think I was able to replicate the problem and I think I have a fix for your issue. The current version that has a potential fix you can try is [3.0.4-beta](https://www.npmjs.com/package/vue3-marquee/v/3.0.4-beta). 

This is the example I tried btw:
```html
<div style="display: flex">
    <Vue3Marquee :clone="true" :duration="1"> 123 </Vue3Marquee>
</div>
```
Please let me know if this works for you. Sorry for being late. ❤️

**Comment by megasanjay** [comment]
@Patrick-Sachs Added a reference in the docs for you: https://vue3-marquee.vercel.app/examples.html#_13

**Comment by megasanjay** [comment]
If this version works for you, please let me know and I'll merge it into the latest version.
