### ISSUE TITLE
`onComplete` & `onLoopComplete` not working

### ISSUE THREAD

**Issue by CRooi** [megasanjay/vue3-marquee#133]
Description:
I am using the `vue3-marquee` library and have set up a component with the `onComplete` prop. However, it is not working as expected and instead of triggering when the animation completes, it is triggered when the page loads. Here is the code I am using:

```
<template>
    <Vue3Marquee :pauseOnClick="true" :duration="1" :onComplete="a()">
        <div>123</div>
    </Vue3Marquee>
</template>

<script setup lang="ts">
import { Vue3Marquee } from 'vue3-marquee'
import 'vue3-marquee/dist/style.css'

let a = () => {
    console.log('complete')
}
</script>
```

Steps to reproduce:
1. Set up a component using `vue3-marquee` library
2. Use the `onComplete` prop to trigger a function when animation completes
3. Load the page and observe that the `onComplete` function is triggered immediately

Expected behavior:
The `onComplete` function should only be triggered when the animation completes, not when the page loads.

Actual behavior:
The `onComplete` function is triggered immediately when the page loads, instead of when the animation completes.

Please help me resolve this issue. Thank you.

**Comment by CRooi** [comment]
use `:onOnComplete="a" :onOnLoopComplete="a"` can solve this problem.

**Comment by megasanjay** [comment]
I could probably improve this for better cases where its only one loop. Let me look into it
