### ISSUE TITLE
Typescript support

### ISSUE THREAD

**Issue by Pacheco95** [megasanjay/vue3-marquee#2]
First of all, thank you for building this library.

Would be nice to have a typescript support even having a good documentation.

**Comment by megasanjay** [comment]
Hi @Pacheco95. I just released a new version of this library that was rewritten to include typescript support. Would you be able to use this in a ts project and let me know if there are any issues? 
The version is 2.0.1-beta

**Comment by ioShinigami** [comment]
> Hi @Pacheco95. I just released a new version of this library that was rewritten to include typescript support. Would you be able to use this in a ts project and let me know if there are any issues? The version is 2.0.1-beta

Id be willing to test this

**Comment by Pacheco95** [comment]
Oh, hi. I'll check it out. Thanks

**Comment by Pacheco95** [comment]
@megasanjay I have updated the package to v2.0.1-beta. The code compiles and works well, but autocompletion is not working.

Try to define the props like this and test if autocomplete will work:

This is an SFC example of my project

```vue
<script setup lang="ts">

const {offset, ticker} = defineProps<{ ticker: string, offset: number }>()

const roundedOffset = offset.toFixed(2)

const bgColorClass = {
  'bg-red-600': offset < 0,
  'bg-gray-400': offset === 0,
  'bg-green-500': offset > 0
}

</script>

<template>
  <span :class="['inline-block font-bold w-40 text-center text-white py-1 px-2 border-gray-300 border border-r-0', bgColorClass]">
    <span class="uppercase pr-2">{{ ticker }}</span>

    <span>
      <span v-if="roundedOffset > 0">+</span>
      <span>{{ roundedOffset }}%</span>
    </span>
  </span>
</template>
```

**Comment by megasanjay** [comment]
Hi @Pacheco95 Thank you for the example. I just updated the library to use `defineProps` and changed my script setup syntax as well. Let me know if this works better for you.

**Comment by megasanjay** [comment]
Update to the latest version of the library (v3.0.3) to add TS support. Check out the instructions on how to use this new version here: https://vue3-marquee.vercel.app/
