### ISSUE TITLE
When scrolling vertically, the style width attribute should be set to auto

### ISSUE THREAD

**Issue by mmclofe** [megasanjay/vue3-marquee#215]
![image](https://github.com/megasanjay/vue3-marquee/assets/44460247/d1965e82-1bb9-41d7-80c0-76ad9cd64343)
When scrolling vertically, the style width attribute should be set to auto

**Comment by megasanjay** [comment]
Could you give your parent container a width? I believe that should handle that. As for your screenshot, I can't seem to replicate that. The one on the examples page seems to work fine: 
![image](https://github.com/megasanjay/vue3-marquee/assets/21206996/8e087ccf-96eb-43f0-b190-c862354fd2f6)
