### ISSUE TITLE
Can provide a step parameter and a stepItemHeight parameter for step-by-step scrolling

### ISSUE THREAD

**Issue by leleccccc** [megasanjay/vue3-marquee#246]
I Want a step-by-step scrolling effect

**Comment by megasanjay** [comment]
If you need more functionality, using a carousel component might be better for your use case. Two that I would suggest are the [vue3-carousel](https://ismail9k.github.io/vue3-carousel/) or [egjs/vue-flicking](https://naver.github.io/egjs-flicking/).
