### ISSUE TITLE
Looping doesn't work, just freezes page

### ISSUE THREAD

**Issue by jenyaftw** [megasanjay/vue3-marquee#264]
**Describe the bug**
Looping doesn't work, it just freezes page.

```
[Violation] Forced reflow while executing JavaScript took <N>ms
```

In console

**To Reproduce**

1. Create a marquee with this code:

```vue
<template>
  <div class="absolute z-50 right-32 bottom-32 flex flex-row space-x-8 max-h-screen overflow-hidden">
    <Vue3Marquee :clone="true">
      <div class="w-16 h-16 mr-8 flex items-center justify-center rounded-full bg-[#1e1e1e]">
        hello
      </div>

      <div class="w-16 h-16 mr-8 flex items-center justify-center rounded-full bg-[#1e1e1e]">
        bye
      </div>
    </Vue3Marquee>
  </div>
</template>
```

3. Set `loop` to true
4. Run project

**Expected behavior**
Should loop elements and scroll through them

**Screenshots**

https://github.com/megasanjay/vue3-marquee/assets/24240873/89a6cb20-91c0-4fcb-88c5-c1589de0ede3

- OS: macOS
- Browser: Brave
- Version: 1.59.117

**Comment by megasanjay** [comment]
That is so strange. Reopening this to see if this is still happening

**Comment by megasanjay** [comment]
Also just adding that loop takes an integer for the number of instances. `0` aka infinite animations is the default.

**Comment by megasanjay** [comment]
And copying your example into my local playground works with no issues. I set loop to 0 on my side (but also works without it being set to anything) @JenyaFTW tagging incase you missed this
