### ISSUE TITLE
Images don't display without human input

### ISSUE THREAD

**Issue by tintin10q** [megasanjay/vue3-marquee#28]
**Describe the bug**
When having images on the marque they don't display after some time until there is input form a human. The images also do not show the alt tag. It happens both on mobile phones and on desktops. 

**To Reproduce**
```vue
<template>
 <vue3-marquee :duration="images.length * 2" direction="reverse" >
          <div v-for="image in images" style="height: 10rem; width: 10rem">
            <img
              :src="image.url"
              :alt="image.alt"
              width="10rem"
              height="10rem"
            />
          </div>
        </vue3-marquee>
</template>

<script>
export default {
  name: "ImageMarquee",
data() { return {
   images: [
{ url: "https://i.scdn.co/image/ab67616d0000b273582e9468816fb5c756af2e57", alt: "See the Light" },
{ url: "https://i.scdn.co/image/ab67616d0000b273d10aa62551fcacbfcbf080e6", alt: "I Feel Love" },
{ url: "https://i.scdn.co/image/ab67616d0000b27360d6fa857326b42347a02f2f", alt: "Honolulu" },
{ url: "https://i.scdn.co/image/ab67616d0000b273355bf68fa788b6d401195b43", alt: "Birthday" },
{ url: "https://i.scdn.co/image/ab67616d0000b273790ed852cb7ff16f747f1cb0", alt: "Put Your Records On - Extended" },
{ url: "https://i.scdn.co/image/ab67616d0000b27359518e073a73c42b539c016e", alt: "Drug" },
{ url: "https://i.scdn.co/image/ab67616d0000b2733a298c3616105dc74f25f44e", alt: "Spliff Break" },
{ url: "https://i.scdn.co/image/ab67616d0000b273758a3b6adc50476dbf3d854c", alt: "Satellites" },
{ url: "https://i.scdn.co/image/ab67616d0000b273aaf9b6f079044a34219c3f6d", alt: "Insight" },
{ url: "https://i.scdn.co/image/ab67616d0000b273808911b13ac4a9f2767b0327", alt: "You See" },
{ url: "https://i.scdn.co/image/ab67616d0000b273ca430ba8cd161c0b99c555c7", alt: "Virtual Connectives" },
{ url: "https://i.scdn.co/image/ab67616d0000b273fe9c5fb6e783d2e912b8b0e6", alt: "Microwave Love (feat. Black Rose)" },
{ url: "https://i.scdn.co/image/ab67616d0000b2736a914f59a9ed1f82e64f52e0", alt: "Tonic Water" },
{ url: "https://i.scdn.co/image/ab67616d0000b273ec4adddeec6b615c14cc16ca", alt: "What You Need" },
{ url: "https://i.scdn.co/image/ab67616d0000b273f1814f1b76df2fa196e4f45e", alt: "Queen Tings" },
{ url: "https://i.scdn.co/image/ab67616d0000b2737bc631e0077b1b10012c53f2", alt: "High With Me" },
{ url: "https://i.scdn.co/image/ab67616d0000b2730b1804895a3ce499c4212bca", alt: "If You Want Me to Stay" },
{ url: "https://i.scdn.co/image/ab67616d0000b273660ee24281a547103f466ff5", alt: "SOS (feat. Aloe Blacc)" },
{ url: "https://i.scdn.co/image/ab67616d0000b273a59b7f91e32078ab2015ac1e", alt: "Up All Night - Marlin Remix" },
{ url: "https://i.scdn.co/image/ab67616d0000b2734ba905686e42400b51a64964", alt: "Promises - Delusion Remix" },
{ url: "https://i.scdn.co/image/ab67616d0000b273eeaf53d6704e7f2cc10cdfe1", alt: "Yep (DJ Greem Remix)" },
{ url: "https://i.scdn.co/image/ab67616d0000b27306e542a76d9d025ecd441fc0", alt: "I Know" },
{ url: "https://i.scdn.co/image/ab67616d0000b273afe4f3225228970213f04ed4", alt: "Butterfly - HotSix Remix" },
{ url: "https://i.scdn.co/image/ab67616d0000b27333cb38e569c02a7e256d0567", alt: "Bucket" },
{ url: "https://i.scdn.co/image/ab67616d0000b273d390959718fdaab2d460f705", alt: "The Rubberband Man" },
]
}
}
}
</script>
```
**Expected behavior**
I expected the images to stay visible. 

**Screenshots**
![image](https://user-images.githubusercontent.com/24190849/166299487-6463c975-70f2-45b4-b455-be166f74b1e1.png)

**Desktop (please complete the following information):**

- OS: Windows
- Browser: Vivaldi
- Version: 5.2.2623.41 (Stable channel) (64-bit) 

**Additional context**
It is not like the browser could not fetch the image it just decides not to for some reason. There is no alt tag which would indicate that the browser did not fetch the image. Do you think this is an issue with your component?

**Comment by megasanjay** [comment]
Your images should not be affected by the marquee. This component is just a container so it should not be affected. I see two potential issues with your img component. 

1. Your `img` tag `width` and `height` attribute should be a number. It seems like you are using a CSS unit that would not work in this case. https://developer.mozilla.org/en-US/docs/Web/HTML/Element/img#attr-height
2. You might not have enough content to fill the space. For something like this, you can use the `:clone='true'` attribute if needed. 

Adding a sandbox link here for you: https://codesandbox.io/s/dreamy-hooks-3sq7qo?file=/src/App.vue
All the alt attributes work here as well.

**Comment by tintin10q** [comment]
Thank you for the really quick reply! I will let you know if it is not working for me. I had no idea you couldn't use css units in the image props.

**Comment by tintin10q** [comment]
It seems like it was indeed the css. It might have also had something to do with the v-img I was using from vuetify. Thank you so much for the jsfiddle that really helped me out!
