### ISSUE TITLE
reverse is not doing great

### ISSUE THREAD

**Issue by pmnzt** [megasanjay/vue3-marquee#295]
**Describe the bug**
when reverse is set to true, the text instead of lopping it then just stops when the loop completes and starts over, however this is not the same case with 'normal'.

**To Reproduce**
```js
    <Vue3Marquee :duration="7" :direction="dir == 'rtl' ? 'reverse' : 'normal'">
       This is English text but it is gonna be in arabic sometime
    </Vue3Marquee>
```

**Expected behavior**
Should work exactly as normal but in reverse.

**Screenshots**

**Desktop (please complete the following information):**

- OS: Debian 12
- Browser FireFox
- Version 122.0.1

**Smartphone (please complete the following information):**

**Additional context**

**Comment by megasanjay** [comment]
I just ran a quick test to see if using reverse direction causes and issue. It works okay on my side. Is the text and/or the direction prop dynamically changing?

**Comment by HELLC--** [comment]
@pmnzt  i fix this problem by this change.
`:root[lang|='ar'] .vue3-marquee.horizontal {
  justify-content: flex-end;
}`
