### ISSUE TITLE
Styles don't seem to work in nuxt 3.10.3, vue 3.4.19

### ISSUE THREAD

**Issue by youkei-zzz** [megasanjay/vue3-marquee#296]
Styles don't seem to work in nuxt 3.10.3, vue 3.4.19
<img width="432" alt="image" src="https://github.com/megasanjay/vue3-marquee/assets/101049479/510eaf0f-0a0a-4462-971a-0f71cc13dd67">

<img width="920" alt="image" src="https://github.com/megasanjay/vue3-marquee/assets/101049479/55474ca4-8bc5-49ef-8137-f3c5f817b375">

<img width="930" alt="image" src="https://github.com/megasanjay/vue3-marquee/assets/101049479/9d818cb9-4498-423c-b8ec-0f689547d6d4">

<img width="1279" alt="image" src="https://github.com/megasanjay/vue3-marquee/assets/101049479/9db50bdd-d868-427d-b86e-b7aac7e80b9a">

**Comment by youkei-zzz** [comment]
Sorry, I made a mistake, it does work. This is a great library and I apologize for my carelessness

**Comment by megasanjay** [comment]
All good! :)
