### ISSUE TITLE
Nuxt 3  Error: Pre-transform error: Missing "./dist/style.css" specifier in "vue3-marquee" package

### ISSUE THREAD

**Issue by molaei2000** [megasanjay/vue3-marquee#297]
**Describe the bug**
Nuxt 3.10.3
Vue 3.4
Error message: Pre-transform error: Missing "./dist/style.css" specifier in "vue3-marquee" package  

**To Reproduce**
I try to migrate from v3 to v4

1. npm uninstall vue3-marquee
2. npm install vue3-marquee@latest --save
3. 
![image](https://github.com/megasanjay/vue3-marquee/assets/56272245/5e827c14-a248-4c2f-9b7d-43bad02396b3)

4. npm run dev
5. See error
6. ![image](https://github.com/megasanjay/vue3-marquee/assets/56272245/e370c76a-1d99-4473-9767-e4062efff574)
7. 
![image](https://github.com/megasanjay/vue3-marquee/assets/56272245/7aee09d4-8341-42e0-84db-a0f645ddb757)

**Screenshots**
![image](https://github.com/megasanjay/vue3-marquee/assets/56272245/e370c76a-1d99-4473-9767-e4062efff574)

**Desktop (please complete the following information):**

- OS: windows
- Browser chrome

**Comment by megasanjay** [comment]
Which version of the library are you using?
 I would upgrade to v4 https://vue3-marquee.vercel.app/introduction/nuxt-3
