### ISSUE TITLE
Whether or not step scrolling is supported？

### ISSUE THREAD

**Issue by xiaofei3062** [megasanjay/vue3-marquee#308]
Is there a property that supports step scrolling, or a case?

**Comment by megasanjay** [comment]
There is not scrolling support. I think a carousel might be better for your usecase

**Comment by xiaofei3062** [comment]
Hopefully it will support next step scrolling

**Comment by megasanjay** [comment]
There won't be steps in this library. You can use https://ismail9k.github.io/vue3-carousel/ or https://naver.github.io/egjs-flicking/
