### ISSUE TITLE
Spacing between array elements

### ISSUE THREAD

**Issue by teobais** [megasanjay/vue3-marquee#319]
Does the component support smart spacing between array elements? I'm trying to create a commodities marquee like https://www.brecorder.com/ but default spacing between array elements doesn't help
<img width="274" alt="Screenshot 2024-04-12 at 15 48 15" src="https://github.com/megasanjay/vue3-marquee/assets/5684688/81ad25b0-c707-40cd-9198-70ce8f91b1c5">

**Comment by megasanjay** [comment]
@teobais 
You can a margin or padding to your elements. That should give you more spacing and you can control it via css
