### ISSUE TITLE
PC/WEB can be used, Uniapp unavailable，Cannot auto scroll

### ISSUE THREAD

**Issue by mimimiaomiao1** [megasanjay/vue3-marquee#329]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by megasanjay** [comment]
What is uniapp? are you able to provide a reproduction?

**Comment by OaimIsGnay** [comment]
> What is uniapp? are you able to provide a reproduction?

https://uniapp.dcloud.net.cn/
Can use Vue to develop mobile apps

**Comment by megasanjay** [comment]
Sorry, I haven't taken a look at this yet. ARe you able to create an app on stackblitz or codesandbox for me to test?

**Comment by Gavin-vue** [comment]
请问你最终最终找的哪个插件呀？

**Comment by Gavin-vue** [comment]
找了下uni-ppp确实没合适的
