### ISSUE TITLE
font bold 

### ISSUE THREAD

**Issue by Gavin-vue** [megasanjay/vue3-marquee#333]
When the element scrolls, the mouse hover to the first element, the font of the element will be thicker？

**Comment by HDP2017** [comment]
I also encountered this problem. In my example, if you hover the mouse over "why why why why?", which is the first element, and then leave it, the font becomes bold.

There is my example
https://stackblitz.com/edit/vitejs-vite-zadamu?file=src%2Fcomponents%2FHelloWorld.vue

**Comment by HDP2017** [comment]
> Could you show an example of the issue you are facing? You can use codesandbox or stackblitz to reproduce the issue.

Please take a look at my example

**Comment by Gavin-vue** [comment]
we need to hover the first element (not others), the  element will be thicker.

**Comment by Gavin-vue** [comment]
Can u help to solve the problem?

**Comment by megasanjay** [comment]
Thanks for the reproduction. Will take a look at this.

**Comment by HDP2017** [comment]
> Thanks for the reproduction. Will take a look at this.

hello，Have you found the problem? Is there a solution?

**Comment by megasanjay** [comment]
I'm not entirely sure what the issue is. I can replicate it on my side as well but if I remove the `.card:hover` border style the issue goes away. Although this is not the solution to this problem

**Comment by Gavin-vue** [comment]
.card:hover {
  background: #ffffff;
  border: 1px solid #2a6aff;
}

we have added a background color original.

**Comment by Gavin-vue** [comment]
we need .card:hover backgorund add border style

**Comment by megasanjay** [comment]
Yeah. Setting the background color to the same is what I could find as well. I will keep looking to see what causes this issue. I think the border on hover is somehow causing a layout shift.

**Comment by Gavin-vue** [comment]
> Yeah. Setting the background color to the same is what I could find as well. I will keep looking to see what causes this issue. I think the border on hover is somehow causing a layout shift.

 Is there a solution to this problem，please?

**Comment by Gavin-vue** [comment]
Is there a solution to this problem，please?
