### ISSUE TITLE
animate-on-overflow-only cause constant flickering

### ISSUE THREAD

**Issue by GetemJay** [megasanjay/vue3-marquee#342]
**Describe the bug**
When the parent determines the width through flex:1, setting animate-on-overflow-only will cause constant flickering

**Desktop (please complete the following information):**

- OS: [e.g. iOS] Macos
- Browser [e.g. chrome, safari] chrome
- Version [e.g. 22] 4.2.0

**Comment by megasanjay** [comment]
Could you provide a  reproduction?

**Comment by GetemJay** [comment]
> Could you provide a reproduction?

https://codesandbox.io/p/devbox/kind-gagarin-2n7tpm?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clzgc7onk00073b6j3m01514i%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clzgc7onk00023b6jlvejnbcp%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clzgc7onk00043b6jdevdj83t%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clzgc7onk00063b6jjfrgvy2r%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clzgc7onk00023b6jlvejnbcp%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clzgc7onj00013b6jcofuz82k%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FREADME.md%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522clzgc8top00023b6igd0y23uy%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A17%252C%2522startColumn%2522%253A43%252C%2522endLineNumber%2522%253A17%252C%2522endColumn%2522%253A43%257D%255D%252C%2522filepath%2522%253A%2522%252Fsrc%252FApp.vue%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clzgc7onk00023b6jlvejnbcp%2522%252C%2522activeTabId%2522%253A%2522clzgc8top00023b6igd0y23uy%2522%257D%252C%2522clzgc7onk00063b6jjfrgvy2r%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clzgc7onk00053b6jt5si1cf6%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522pnpm%2520run%2520dev%2522%252C%2522port%2522%253A5173%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clzgc7onk00063b6jjfrgvy2r%2522%252C%2522activeTabId%2522%253A%2522clzgc7onk00053b6jt5si1cf6%2522%257D%252C%2522clzgc7onk00043b6jdevdj83t%2522%253A%257B%2522id%2522%253A%2522clzgc7onk00043b6jdevdj83t%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clzgc7onk00033b6jz1y7wp24%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522pnpm%2520run%2520dev%2522%257D%252C%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522pnpm%2520install%2520vue3-marquee%25404.2.1%2522%252C%2522id%2522%253A%2522clzgdamy5005p3b6inmdjba3o%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clzgc7onk00033b6jz1y7wp24%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D

**Comment by GetemJay** [comment]
But I know how to avoid this problem. Setting flex:1 to the parent .left of the marquee-box can solve it.

**Comment by megasanjay** [comment]
I'm glad that you were able to fix it. I will try to create an example for a Spotify-style UI, it looks like you are going for, when I get some time.
