### ISSUE TITLE
onOverflowCleared and onOverflowDetected are swapped

### ISSUE THREAD

**Issue by adampanger** [megasanjay/vue3-marquee#346]
Hey! It seems the `onOverflowDetected` and `onOverflowCleared` are swapped. Currently, when the animation is running due to overflow, the `onOverflowCleared` is emitted. I created a PR that addresses this issue.  #345

**Comment by megasanjay** [comment]
Thank you for catching that! Fixed in https://github.com/megasanjay/vue3-marquee/pull/345
