### ISSUE TITLE
`on-loop-complete` is out of sync with real animation

### ISSUE THREAD

**Issue by Beaterie** [megasanjay/vue3-marquee#355]
**Describe the bug**
`OnLoopComplete` event fails triggering at the right time when a `delay` prop is used or the animation is paused in between.

**To Reproduce**

1. Define a `delay > 0 `
2. Give `@on-loop-complete` a console log (or with via an external ref and watch with console log) OR trigger the `paused` property during the animation via a button e.g.
3. See in console the triggered log which doesn't fit to the moment of the loop. Event is not connected to the real animation status.

**Expected behavior**
`OnLoopComplete` should consider both, a defined delay but also a pause in the animation. So far it only depends on a TimeOut which leads to a misalignment of the OnLoopComplete event with the real animation. In this context, the event is useless right now.

**Desktop (please complete the following information):**
- macOs ARM
- Chrome
- Version 128.0.6613.138

**Additional context**

**Comment by megasanjay** [comment]
I had planned to use the x/y position on the page to rework the loop counter but this runs into the same issue with breaking the counter flow. I will try to rework this soon so that it is more accurate.

**Comment by DaryeDev** [comment]
Bump! Having the same issue here trying to loop infinitely when hover, but finish the loop and stop when not.

I have the system, but the onLoopComplete event is inconstant.
