### ISSUE TITLE
features i want to have

### ISSUE THREAD

**Issue by dennischchch** [megasanjay/vue3-marquee#5]
it is possible to set the amount of times for looping items? 
how do I know when it is finished the animation?

**Comment by megasanjay** [comment]
Hi @dennischchch. The loop variable is a css animation count. If you are doing a simple loop on your content with no `pauseOnHover` or `pauseOnClick`, you should be able to use a basic timer to know when the animation ends. I can look into adding an emitted event but I feel that a timeout is probably simpler

**Comment by megasanjay** [comment]
Also, there is a prop provided (`loop`) for controlling the number of loops. 
You can find more information here: https://vue3-marquee.vercel.app/guide.html#loop

**Comment by dennischchch** [comment]
Thank you for your help, I have another question is that when I set loop to 1, it appear two time. 

is it possible to start the animation(text appear from left and move to the right,) from left to right and stop it(then data will be change and start to run again).

Below is my code.

<script lang='ts' setup>

import Vue3Marquee from "vue3-marquee";
import {ref, nextTick} from 'vue';
const  helloArray:string[]= [
        "START",
        "こんにちは",
        "bonjour",
        "안녕하세요", "hello",
        "こんにちは",
        "bonjour",
        "안녕하세요", "hello",
        "こんにちは",
        "bonjour",
        "end"]
        
      


 nextTick(()=>{

   let elements = document.getElementsByClassName("vue3-marquee");
  
     Array.from(elements).forEach(function(element) {
      element.addEventListener('animationend', ()=>{
         console.log("End")
         //load another data and run again
         
      });
    })
  })

</script>
<template>
<div>
 <Vue3Marquee :loop="1" :duration="4" id="vue3-marquee" :delay="1" >
    <span
    
      v-for="(word, index) in helloArray"
      test="a"
      :key="index"
      class="word-style"
      :class="{ word: true, odd: index % 2 === 0, even: index % 2 === 1 }"
    >
      {{ word }}
    </span>
  </Vue3Marquee>

</div>
</template>
<style lang='scss' scoped>
.word-style{
    border: 1px solid green;
}
</style>

**Comment by megasanjay** [comment]
I just tested a `:loop='1'` and it only ran once. 
Your data can change mid animation. Since this library uses slots you can modify data and it should handle it. For the direction of movement, you can determine which way you want it to move: https://vue3-marquee.vercel.app/guide.html#direction 

Would you mind adding that code on codepen.io or codesandbox.io and sending me the link? I can take a look at it.

**Comment by megasanjay** [comment]
@OctopussyO This library does not have support for Vue 2. However, you can use this library: https://github.com/YishaiBerg/vue-dynamic-marquee which I believe is built with Vue 2 in mind.
