### ISSUE TITLE
鼠标经过时，跑马灯会暂停，但是当我鼠标按下时，跑马灯又会自己跑动了

### ISSUE THREAD

**Issue by Kyensss** [megasanjay/vue3-marquee#67]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by megasanjay** [comment]
What happens when you try both `pauseOnHover` and `pauseOnClick` at the same time?

**Comment by megasanjay** [comment]
Keeping this open
