### ISSUE TITLE
Possible to add scrollable feature to allow user to  drag to passed/previous content.

### ISSUE THREAD

**Issue by thesupermeng** [megasanjay/vue3-marquee#76]
dear megasanjay, i love you

**Comment by thesupermeng** [comment]
Something like this  https://stackoverflow.com/a/48021894/13164506. Thanks you @megasanjay. Vue love you.

**Comment by megasanjay** [comment]
I can take a look at it. Is there any reason you can't use a carousel instead?

**Comment by thesupermeng** [comment]
> I can take a look at it. Is there any reason you can't use a carousel instead?

yo @megasanjay.. thanks for the reply.

 It is because Carousel unable to make a smooth linear transition like Marquee, if override the css to do so, during the transition time it's not draggable. (i think is because during the css animation, the mouse/touch event is not detactable ). Hope this clear.
 
  Once again, thank you sanjay.

**Comment by thesupermeng** [comment]
Update: today tried a package named "swiper.js", already very close but still unable to get smooth playback after drag event.


example:
 https://codesandbox.io/s/swiper-freemode-vue-forked-c4v80c
