### ISSUE TITLE
Speed issue with multiple component on same page

### ISSUE THREAD

**Issue by sandyrewa** [megasanjay/vue3-marquee#77]
when use the multiple marquee component on the same page then duration speed is not working same for all component.
For the first component speed is proper but for all other duration is not working.

Example of code 
`<Vue3Marquee :clone="true">
    <img
      :src="img"
      v-for="img in imgArray"
      :key="img"
      class="image"
      width="100"
    />
  </Vue3Marquee>`
 
Please let me know i'm missing anything.

Thanks

**Comment by megasanjay** [comment]
Would you mind adding a reproduction on codesandbox or stackblitz?

**Comment by megasanjay** [comment]
@sandyrewa It should be all independant

**Comment by sandyrewa** [comment]
@megasanjay Thanks for the quick replay, I created a script on code sandbox its working fine but it's not working on my project it may be due to dynamic data I will check and update asap.

**Comment by megasanjay** [comment]
I could see an issue with dynamic data. Maybe I could add a method that refreshes the marquee? Would that be a better solution for you?
