### ISSUE TITLE
While the marquee is paused via hover, the onLoopComplete continues

### ISSUE THREAD

**Issue by Worie** [megasanjay/vue3-marquee#99]
Hello - first of all, thank you for the time you've put so far into this project. 
I've been playing around with the component to fit my needs (more of a live feed with data), and the component is flexible enough for me to achieve my goal. 

One thing that I noticed while working on my piece, is that if you register `onLoopComplete` event handler while at the same time enabling the  `pauseOnHover`, if the user hovers on the marquee (pausing the motion as expected), the internal clock proceeds, and triggers `onLoopComplete` while in fact marquee has been idle for a long period of time now, leading to logic getting out of sync in the long run.

Steps to reproduce: 
- Create a relatively short duration for a marquee, i.e. 5s (can be any, but it's easier to see in that case)
- Register a `console.log` to `onLoopComplete`
- Enable `:pause-on-hover="true"`
- Hover on the component
- Wait for some time, i.e. 20s
- See that the handler has been invoked regardless of animation being paused

I would expect the internal clock to pause when hovering - or, maybe the internal clock can be removed completely if we add an intersection observer to some static, built in hidden element that would be at the end of the loop - and trigger when the element gets out of sight.

Again, thanks for all your hard work with this!

**Comment by megasanjay** [comment]
Thank you for bringing this up. The onLoopComplete is a manual timer implementation but I can make it a more connected part of the component. Let me look into fixing this for you.

**Comment by megasanjay** [comment]
Reopening this so I can take a look at this later.
